/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ajedrez;

/**
 *
 * @author Pablo García 
 */
public class Inicio extends javax.swing.JFrame {

    Ajedrez ajedrez;
    
    public Inicio() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jugadorBlancasTexto = new javax.swing.JLabel();
        jugadorNegrasTexto = new javax.swing.JLabel();
        saludo = new javax.swing.JLabel();
        botonJugar = new javax.swing.JButton();
        caballo = new javax.swing.JLabel();
        rey = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        panelContenedor.setBackground(new java.awt.Color(102, 51, 0));
        panelContenedor.setMaximumSize(new java.awt.Dimension(800, 600));
        panelContenedor.setMinimumSize(new java.awt.Dimension(800, 600));
        panelContenedor.setPreferredSize(new java.awt.Dimension(800, 600));

        jugadorBlancasTexto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jugadorBlancasTexto.setForeground(new java.awt.Color(255, 255, 255));
        jugadorBlancasTexto.setText("Jugador 1 (piezas blancas)");

        jugadorNegrasTexto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jugadorNegrasTexto.setForeground(new java.awt.Color(255, 255, 255));
        jugadorNegrasTexto.setText("Jugador 2 (piezas negras)");

        saludo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        saludo.setForeground(new java.awt.Color(255, 255, 255));
        saludo.setText("SISTEMA DE AYUDA A LA DECISIÓN DE AJEDREZ");

        botonJugar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonJugar.setText("JUGAR");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(caballo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugadorNegrasTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugadorBlancasTexto))
                        .addGap(40, 40, 40)
                        .addComponent(rey, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rey)
                    .addComponent(caballo))
                .addGap(18, 18, 18)
                .addComponent(saludo)
                .addGap(74, 74, 74)
                .addComponent(jugadorBlancasTexto)
                .addGap(18, 18, 18)
                .addComponent(jugadorNegrasTexto)
                .addGap(77, 77, 77)
                .addComponent(botonJugar)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed

        /*
        String nombreBlancas = jugadorBlancasEntrada.getText();
        String nombreNegras = jugadorNegrasEntrada.getText();

        int opcion = listaTiempo.getSelectedIndex();
        */

        String nombreBlancas = "Mueven Blancas";
        String nombreNegras = "Mueven Negras";
        int opcion = 1;

        ajedrez = new Ajedrez(nombreBlancas,nombreNegras, opcion);
        this.dispose();

    }//GEN-LAST:event_botonJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugar;
    private javax.swing.JLabel caballo;
    private javax.swing.JLabel jugadorBlancasTexto;
    private javax.swing.JLabel jugadorNegrasTexto;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JLabel rey;
    private javax.swing.JLabel saludo;
    // End of variables declaration//GEN-END:variables
}
